class LangPackage {
  Map<String, String> langEN = {
    'app': 'Housework Manager',
    'husband': 'Husband',
    'wife': 'Wife',
    'new_task': 'New Task',
    'new_master': 'New Master',
    'summary': 'Summary',
    'calendar': 'Calendar',
    'task': 'Task',
    'master': 'Master',
    'confirm': 'Confirm',
    'confirm_txt': 'Do you want to remove?',
    'yes': 'Yes',
    'no': 'No',
    'master_editor': 'Master Editor',
    'shot': 'Shot',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'daily': 'Daily',
    'weekday': 'Weekday',
    'weekend': 'WeekEnd',
    'points': 'Points',
    'type': 'Type',
    'save': 'Save',
    'charge': 'Charge',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'line_title': 'Last 7 days summary',
    'pie_title': 'Workload balance',
    'email': 'Email',
    'password': 'Password',
    'login': 'Login',
    'logout': 'Logout',
    'user': 'User Login',
    'welcome': 'Welcome to Housework Manager!',
    'error': 'Login Error',
  };

  Map<String, String> langJP = {
    'app': 'Housework Manager',
    'husband': '夫',
    'wife': '妻',
    'new_task': '新しいタスク',
    'new_master': '新しいマスター',
    'summary': 'レポート',
    'calendar': 'スケジュール',
    'task': 'タスク',
    'master': 'マスター',
    'confirm': '確認',
    'confirm_txt': '削除しますか？',
    'yes': 'はい',
    'no': 'いいえ',
    'master_editor': 'マスター編集',
    'shot': '単発',
    'weekly': '週次',
    'monthly': '月次',
    'daily': '日次',
    'weekday': '平日',
    'weekend': '週末',
    'points': 'ポイント',
    'type': '種類',
    'save': '保存',
    'charge': '担当',
    'start_date': '開始日',
    'end_date': '終了日',
    'line_title': '先週の実績',
    'pie_title': '分担バランス',
    'email': 'メールアドレス',
    'password': 'パスワード',
    'login': 'ログイン',
    'logout': 'ログアウト',
    'user': 'ユーザーログイン',
    'welcome': 'ようこそ！',
    'error': 'ログインエラー',
  };

  getNameString() {
    return langJP;
  }

}